### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by skygering** [skygering/land-ocean-warming-ratio#1]
### Part 0
**Training and setup**
- [x] Background on land/ocean warming ratio until explainable
- [x] Training with Git and Github
- [x] Training with R and RMarkdown
- [x] Install CDO
- [x] Read about netCDF
- [x] Download Panoply
- [x] Training with CDO
- [x] Access to pic
- [x] Training with netcdf

### Part 1
**Process one or more CIMP6 model outputs to calculate the land/ocean warming ratio**
- [x] Experiment with test CMIP5 data
- [x] Reading about CMIP6
- [x] Write script in cdo (with R driver, after debugging in bash)

- Land and ocean averages of 2 m air temperature
- Need area file and land/ocean mask
- For model and year ensemble, extract 2 m air temperature, compute annual average via cdo, multiply by land mask, and compute area-weighted mean -> land temperature

- [x] Plot over time by model/ensemble

### Part 2
**Implement in Hector**
- [x] Read about Hector's structure
- [x] Build Hector in VS (Boost)
- [x] Adding a temperature parameter for land/ocean warming ratio into the model's temperature component
- [x] Calculate the land and ocean temp (need to know global ratio of land/ocean area)
- [x] Investigate downstream components and integrate
- [x] Write to output stream
- [x] Add bindings to change parameter and get output via R interface
- [x] Add R package test code to verify that global temperature shouldn't change
- [x] Doing comparative runs for RCPs of ratio=1 versus ratio={CMIP6}

**Comment by bpbond** [comment]
Looks great @skygering 👏

**Comment by skygering** [comment]
Useful for using netCDF files in R: https://www.youtube.com/watch?v=5KbxWsQbAjs
Making gg2plots: http://www.sthda.com/english/wiki/ggplot2-line-plot-quick-start-guide-r-software-and-data-visualization
Git documentation: https://git-scm.com/docs/git-checkout
